server:
  port: 8380
  ssl:
    key-store: src/main/resources/springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password

spring:
  application:
    name: find-guide
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/find_guide
    username: find_guide
    password: find_guide
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariDbPool

bot:
  username: find_guide_bot
  token: 5957262303:AAEbQPnIvl6EGoOXswWn8xP1Dhvz8PirX-E
